title: CBER Crafting the Cryptoeconomy Conference
logo:
  text: |
    CRYPTO AND BLOCKCHAIN<br/>
    ECONOMICS RESEARCH FORUM
img: 'logo.svg'  # inside /assets/images/
mainurl: 'https://www.cber-forum.org/'
description: 
baseurl: ""
url: https://ctce.cber-forum.org

theme: jekyll-nagymaros

copyright: CBER-Forum
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
