title: 4th Annual CBER Conference
description: 
baseurl: ""
url: https://cber-forum.github.io/conference2024v2

theme: jekyll-nagymaros
# remote_theme: piazzai/jekyll-nagymaros

copyright: CBER-Forum
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
