title: CBER Crafting the Cryptoeconomy Conference
logoimg: ''  # logo.svg inside /assets/images/
logoname: |
  <div style="display: table;"> <i style="display: block; width: 50px; text-align: center; display: table-cell; vertical-align: middle;">i</i> <span style="display: block; display: table-cell;">CRYPTO AND BLOCKCHAIN<br/>ECONOMICS RESEARCH FORUM</span> </div>
mainurl: 'https://www.cber-forum.org/'
description: 
baseurl: ""
url: https://ctce.cber-forum.org

theme: jekyll-nagymaros

copyright: CBER-Forum
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
