title: CBER Crafting the Cryptoeconomy Conference
logo:
  img: 
  name: |
    CRYPTO AND BLOCKCHAIN
    ECONOMICS RESEARCH FORUM
mainurl: 'https://www.cber-forum.org/'
description: 
baseurl: ""
url: https://ctce.cber-forum.org

theme: jekyll-nagymaros

copyright: CBER-Forum
indexing: true

permalink: pretty

exclude:
  - LICENSE
  - README.md
